// SPDX-License-Identifier: GPL-2.0-or-later

/***************************************************************************
 *   Copyright (C) 2005 by Dominic Rath                                    *
 *   Dominic.Rath@gmx.de                                                   *
 *                                                                         *
 *   Copyright (C) 2008 by Spencer Oliver                                  *
 *   spen@spen-soft.co.uk                                                  *
 *                                                                         *
 *   Copyright (C) 2011 by Andreas Fritiofson                              *
 *   andreas.fritiofson@gmail.com                                          *
 ***************************************************************************/

#include "helper/log.h"
#include "target/armv7m.h"
#include <stdint.h>
#include <time.h>
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <string.h>

#include "imp.h"
#include <helper/binarybuffer.h>
#include <target/algorithm.h>
#include <target/cortex_m.h>

#include <target/image.h>
#include <helper/configuration.h>
#include "target/breakpoints.h"

#include <helper/time_support.h>
/* timeout values */

#define FLASH_WRITE_TIMEOUT 10
#define FLASH_ERASE_TIMEOUT 100

#define PROGRAM_BKPT_OFFSET 0x08
#define PROGRAM_ARGS_OFFSET 0x10

static uint8_t fls_algo_buffer[] = 
{
/* Autogenerated with ./src/helper/bin2char.sh */
0x02,0x22,0x0d,0x4b,0x10,0xb5,0x1a,0x62,0x0f,0x32,0x9a,0x63,0x80,0x22,0x01,0x21,
0xd2,0x05,0x53,0x6e,0x8b,0x43,0x53,0x66,0x08,0x4a,0x13,0x69,0x8b,0x43,0x13,0x61,
0x00,0xf0,0x70,0xf8,0x06,0x4b,0x1b,0x68,0x01,0x2b,0x03,0xd1,0x05,0x4b,0x18,0x68,
0x00,0xf0,0x53,0xf8,0x00,0xbe,0xf3,0xe7,0x00,0x20,0x00,0x40,0x00,0x04,0x00,0x40,
0x70,0x01,0x02,0x00,0x6c,0x01,0x02,0x00,0xf8,0xb5,0xc0,0x46,0xf8,0xbc,0x08,0xbc,
0x9e,0x46,0x70,0x47,0xf8,0xb5,0xc0,0x46,0xf8,0xbc,0x08,0xbc,0x9e,0x46,0x70,0x47,
0x0d,0x4b,0x83,0xf3,0x08,0x88,0xff,0xf7,0xcb,0xff,0x0c,0x48,0x0c,0x4a,0x00,0x21,
0x12,0x1a,0x92,0x10,0x00,0xf0,0x2c,0xf8,0x0a,0x48,0x0b,0x4a,0x0b,0x49,0x12,0x1a,
0x92,0x10,0x00,0xf0,0x1b,0xf8,0x0a,0x48,0x0a,0x4a,0x0b,0x49,0x12,0x1a,0x92,0x10,
0x00,0xf0,0x14,0xf8,0xff,0xf7,0xb4,0xff,0x00,0x20,0x02,0x00,0x6c,0x01,0x02,0x00,
0x78,0x01,0x02,0x00,0x04,0x01,0x02,0x00,0x6c,0x01,0x02,0x00,0x04,0x01,0x02,0x00,
0x00,0x00,0x02,0x00,0x00,0x00,0x02,0x00,0x00,0x00,0x02,0x00,0x00,0x23,0x30,0xb5,
0x9a,0x42,0x00,0xd1,0x30,0xbd,0x9c,0x00,0x0d,0x59,0x01,0x33,0x05,0x51,0xf7,0xe7,
0x01,0x3a,0x00,0xd2,0x70,0x47,0x02,0xc0,0xfa,0xe7,0x80,0x22,0x00,0x23,0x52,0x05,
0x90,0x42,0x5b,0x41,0xc0,0x22,0x5b,0x42,0x1b,0x0c,0x92,0x02,0x1b,0x04,0xc0,0x03,
0x9b,0x18,0x40,0x0c,0x18,0x43,0x80,0x23,0x10,0xb5,0xdb,0x05,0x58,0x61,0x00,0xf0,
0x0d,0xf8,0x10,0xbd,0x00,0x22,0x01,0x4b,0x1a,0x70,0x70,0x47,0x74,0x01,0x02,0x00,
0x01,0x4b,0x18,0x78,0xc0,0xb2,0x70,0x47,0x74,0x01,0x02,0x00,0x70,0xb5,0x00,0xf0,
0x1c,0xf8,0x04,0x00,0xff,0xf7,0xf4,0xff,0x00,0x28,0x04,0xd0,0x20,0x00,0x00,0xf0,
0x18,0xf8,0x03,0x20,0x70,0xbd,0x80,0x25,0x01,0x26,0xed,0x05,0xeb,0x69,0x20,0x00,
0x33,0x43,0xeb,0x61,0x00,0xf0,0x0d,0xf8,0x2b,0x6f,0x33,0x42,0xfc,0xd1,0xff,0xf7,
0xdf,0xff,0x00,0x28,0xee,0xd0,0x07,0x20,0xec,0xe7,0xef,0xf3,0x10,0x80,0x72,0xb6,
0x70,0x47,0x00,0x28,0x00,0xd1,0x62,0xb6,0x70,0x47,0x00,0x00,

};

static uint32_t __BKPT = 0x20034;

struct cw32_options
{
	uint8_t rdp;
	uint8_t user;
	uint16_t data;
	uint32_t protection;
};

struct fls_algo_param
{
	volatile uint32_t func;
	volatile uint32_t func_size;
	volatile uint32_t func_end;
	volatile bool init;
};
static struct fls_algo_param fls_algo_params = {0};
struct cw32_flash_bank
{
	struct cw32_options option_bytes;
	int ppage_size;
	bool probed;

	bool has_dual_banks;
	/* used to access dual flash bank stm32xl */
	bool can_load_options;
	uint32_t register_base;
	uint8_t default_rdp;
	int user_data_offset;
	int option_offset;
	uint32_t user_bank_size;
};

#define CW2213_FLS_ALGO_FILE		"../cw_fls_algo/cw2213_flash_algo.elf"
#define CW2213_ROM_FILE				"../cw_fls_algo/cw2213_rom.elf"
static int cw32_write_block(struct flash_bank *bank, const uint8_t *buffer,
							  uint32_t address, uint32_t hwords_count);
static int cw32_load_fls_algo(struct flash_bank *bank);
/* flash bank stm32x <base> <size> 0 0 <target#>
 */
FLASH_BANK_COMMAND_HANDLER(cw32_flash_bank_command)
{
	if (CMD_ARGC < 6)
		return ERROR_COMMAND_SYNTAX_ERROR;

	struct cw32_flash_bank * cw32_info = malloc(sizeof(struct cw32_flash_bank));

	/* set page size, protection granularity and max flash size depending on family */
	cw32_info->ppage_size = 32;
	cw32_info->probed = false;

	cw32_info->has_dual_banks = false;
	cw32_info->can_load_options = false;
	cw32_info->register_base = 0;// UNUSED set zero
	/* default factory read protection level 0 */
	cw32_info->default_rdp = 0;
	cw32_info->user_data_offset = 0;
	cw32_info->option_offset = 0;
	cw32_info->user_bank_size = bank->size;

	bank->driver_priv = cw32_info;
	/* The flash write must be aligned to a halfword boundary */
	bank->write_start_alignment = bank->write_end_alignment = 2;

	return ERROR_OK;
}

static int cw32_erase(struct flash_bank *bank, unsigned int first,
						unsigned int last)
{
	log_info("%s", __func__);
	int retval = 0;
	struct target *target = bank->target;
	if (!fls_algo_params.init) 
	{
		fls_algo_params.init = true;
		cw32_load_fls_algo(bank);
	}

	int64_t run_algo_start = timeval_ms();

	for (int i = first; i <= last; i++) {
		uint32_t addr = bank->base + bank->sectors[i].offset;

		struct reg_param reg_params[4];
		/* set up parameters */
		init_reg_param(&reg_params[0], "r0", 32, PARAM_IN);
		init_reg_param(&reg_params[1], "r1", 32, PARAM_IN);
		init_reg_param(&reg_params[2], "r2", 32, PARAM_IN);
		init_reg_param(&reg_params[3], "sp", 32, PARAM_IN);

		buf_set_u32(reg_params[0].value, 0, 32, 1);
		buf_set_u32(reg_params[1].value, 0, 32, addr);
		buf_set_u32(reg_params[2].value, 0, 32, 0);
		buf_set_u32(reg_params[3].value, 0, 32, 0x00022000-8);


		/* use alg to write data from work area to NAND chip */
		log_info("erase sector addr %08X", addr);
		struct armv7m_algorithm armv7m_info;	
		armv7m_info.common_magic = ARMV7M_COMMON_MAGIC;
		armv7m_info.core_mode = ARM_MODE_THREAD;	
		struct armv7m_common *armv7m = target_to_armv7m(target);	
		uint32_t res[0x1000] = {1};
		
		target_read_buffer(target, 0x00020170, sizeof(res), res);
		res[0] = 0x10000000;
		target_read_buffer(target, 0x0002016c, sizeof(res), res);
		armv7m->store_core_reg_u32(target, ARMV7M_PC, 0x20000);
		armv7m->load_core_reg_u32(target, ARMV7M_PC, res);
		log_info("PC %08X.", res[0]);
		// target_read_buffer(target, 0x20000, 0x200, res);
		// log_hex("ram", res, 0x200);
		retval = target_run_algorithm(target,
									0, NULL,
									0, NULL,
									0x20000,
									__BKPT,
									10000, &armv7m_info);
		// target_read_buffer(target, 0x20000, 0x200, res);
		// log_hex("ram", res, 0x200);
		armv7m->load_core_reg_u32(target, ARMV7M_PC, res);
		log_info("PC %08X.", res[0]);
		armv7m->load_core_reg_u32(target, ARMV7M_R0, res);
		log_info("R0 %08X.", res[0]);
		target_read_buffer(target, addr, sizeof(res), res);
		log_info("Read back check erase addr %08X : %08X.", addr, res[0]);
		if (retval != ERROR_OK)
			LOG_ERROR("error executing hosted NAND write");

		destroy_reg_param(&reg_params[0]);
		destroy_reg_param(&reg_params[1]);
		// destroy_reg_param(&reg_params[2]);
	}

	log_info("run erase algo %" PRId64 " ms.[%d sectors]", timeval_ms() - run_algo_start, last - first + 1);

	if (retval != ERROR_OK)
	{
		LOG_ERROR("Failed to execute algorithm at 0x%" PRIx32 ": %"PRId32"",
				  fls_algo_params.func_end, retval);
	}

	log_info("%s end", __func__);
	return retval;
}

static int cw32_protect(struct flash_bank *bank, int set, unsigned int first, unsigned int last)
{
	// log_info("%s", __func__);
	return ERROR_FLASH_OPER_UNSUPPORTED;
}

static int cw32_write_block_riscv(struct flash_bank *bank, const uint8_t *buffer,
									uint32_t address, uint32_t words_count)
{
	int64_t write_block_start = timeval_ms();
	// log_info("%s", __func__);
	struct target *target = bank->target;
	int retval = 0;
	uint32_t total_bytes = words_count*4;
	
	struct working_area *source;

	retval = target_alloc_working_area(target, 0x800, &source);
	/* Allocated size is always word aligned */
	if (retval != ERROR_OK) {
		LOG_WARNING("no large enough working area available, can't do block memory writes");
		/* target_alloc_working_area() may return ERROR_FAIL if area backup fails:
		* convert any error to ERROR_TARGET_RESOURCE_NOT_AVAILABLE
		*/
		return ERROR_TARGET_RESOURCE_NOT_AVAILABLE;
	}

	while (words_count > 0)
	{
		uint32_t thisrun_words = 0x800 / 4;

		/* Limit to the amount of data we actually want to write */
		if (thisrun_words > words_count)
			thisrun_words = words_count;

		/* Write data to buffer */
		uint32_t len = thisrun_words * 4;

		// int64_t write_data_start = timeval_ms();
		/* Write data to buffer */
		retval = target_write_buffer(target, source->address,len, buffer);
		// log_info("load program data %" PRId64 " ms.[0x%X bytes]", timeval_ms() - write_data_start, len);
		if (retval != ERROR_OK)
			break;

		struct reg_param reg_params[4];
		/* set up parameters */
		init_reg_param(&reg_params[0], "r0", 32, PARAM_IN);
		init_reg_param(&reg_params[1], "r1", 32, PARAM_IN);
		init_reg_param(&reg_params[2], "r2", 32, PARAM_IN);
		init_reg_param(&reg_params[3], "sp", 32, PARAM_IN);

		buf_set_u32(reg_params[0].value, 0, 32, address);
		buf_set_u32(reg_params[1].value, 0, 32, len);
		buf_set_u32(reg_params[2].value, 0, 32, source->address);
		buf_set_u32(reg_params[3].value, 0, 32, 0x00022000-8);
	
	// armv7m_info.common_magic = ARMV7M_COMMON_MAGIC;
	// armv7m_info.core_mode = ARM_MODE_THREAD;
	// 	/* use alg to write data from work area to NAND chip */
	// 	retval = target_run_algorithm(target,
	// 								0, NULL,
	// 								1, reg_params,
	// 								fls_algo_params.ProgramPage,
	// 								fls_algo_params.ProgramPage_end,
	// 								10000, &armv7m_info);
	// 	if (retval != ERROR_OK)
			// LOG_ERROR("error executing hosted NAND write");

		destroy_reg_param(&reg_params[0]);
		// destroy_reg_param(&reg_params[1]);
		// destroy_reg_param(&reg_params[2]);

		// log_info("run program algo %" PRId64 " ms.", timeval_ms() - write_data_start);
		// uint32_t res[1] = {0};
		// target_read_buffer(target, fls_algo_params.g_error, sizeof(res), res);
		// log_info("run fls program algorithm res %08X.", res[0]);
		
		// uint8_t bbb[0x5000] = {0};
		// target_read_buffer(target,address, len, bbb);
		// log_hex("check fls data",  bbb, 0x10);

		// if (memcmp(buffer, bbb, len)!=0) {
		// 	return ERROR_FAIL;
		// }

		if (retval != ERROR_OK)
		{
			LOG_ERROR("Failed to execute algorithm at 0x%" PRIx32 ": %"PRId32"",
					  address, retval);
			break;
		}

		/* Update counters */
		buffer += thisrun_words * 4;
		address += thisrun_words * 4;
		words_count -= thisrun_words;
	}
	log_info("write block %" PRId64 " ms.[0x%X bytes]", timeval_ms() - write_block_start, total_bytes);

	return retval;
}

/** Writes a block to flash either using target algorithm
 *  or use fallback, host controlled halfword-by-halfword access.
 *  Flash controller must be unlocked before this call.
 */
static int cw32_write_block(struct flash_bank *bank,
							  const uint8_t *buffer, uint32_t address, uint32_t words_count)
{
	struct target *target = bank->target;

	/* The flash write must be aligned to a halfword boundary.
	 * The flash infrastructure ensures it, do just a security check
	 */
	assert(address % 4 == 0);

	int retval;
	retval = cw32_write_block_riscv(bank, buffer, address, words_count);

	if (retval == ERROR_TARGET_RESOURCE_NOT_AVAILABLE)
	{
		/* if block write failed (no sufficient working area),
		 * we use normal (slow) single halfword accesses */
		LOG_WARNING("couldn't use block writes, falling back to single memory accesses");

		while (words_count > 0)
		{
			retval = target_write_memory(target, address, 4, 1, buffer);
			if (retval != ERROR_OK)
				return retval;

			words_count--;
			buffer += 4;
			address += 4;
		}
	}
	return retval;
}

static int cw32_write(struct flash_bank *bank, const uint8_t *buffer,
						uint32_t offset, uint32_t count)
{
	// log_info("%s", __func__);
	// struct target *target = bank->target;
	if (!fls_algo_params.init) 
	{
		fls_algo_params.init = true;
		cw32_load_fls_algo(bank);
	}
	if (bank->target->state != TARGET_HALTED)
	{
		LOG_ERROR("Target not halted");
		return ERROR_TARGET_NOT_HALTED;
	}

	/* The flash write must be aligned to a word boundary.
	 * The flash infrastructure ensures it, do just a security check
	 */
	assert(offset % 4 == 0);
	assert(count % 4 == 0);

	int retval;

	/* write to flash */
	retval = cw32_write_block(bank, buffer, bank->base + offset, count / 4);

	return retval;
}

struct cw32_property_addr
{
	uint32_t device_id;
	uint32_t flash_size;
};

static int cw32_get_property_addr(struct target *target, struct cw32_property_addr *addr)
{
	return ERROR_NOT_IMPLEMENTED;
}

static int cw32_get_device_id(struct flash_bank *bank, uint32_t *device_id)
{
	return ERROR_NOT_IMPLEMENTED;
}

static int cw32_get_flash_size(struct flash_bank *bank, uint16_t *flash_size_in_kb)
{
	return ERROR_NOT_IMPLEMENTED;
}

static int cw32_probe(struct flash_bank *bank)
{
	// log_info("%s", __func__);
	struct cw32_flash_bank *cw32_info = bank->driver_priv;
	uint16_t sector_size = 0x200;

	// LOG_INFO("flash size = %d KiB", bank->size);

	/* did we assign flash size? */
	assert(bank->size != 0xffff);

	free(bank->sectors);
	bank->sectors = NULL;

	free(bank->prot_blocks);
	bank->prot_blocks = NULL;

	bank->num_sectors = bank->size / sector_size;
	bank->sectors = alloc_block_array(0, sector_size, bank->num_sectors);
	if (!bank->sectors)
		return ERROR_FAIL;

	cw32_info->probed = true;

	return ERROR_OK;
}

static int cw32_auto_probe(struct flash_bank *bank)
{
	// log_info("%s", __func__);
	if (((struct cw32_flash_bank *)bank->driver_priv)->probed)
		return ERROR_OK;
	return cw32_probe(bank);
}

static int cw32_protect_check(struct flash_bank *bank)
{
	// log_info("%s", __func__);
	return ERROR_OK;
}

static int get_cw32_info(struct flash_bank *bank, struct command_invocation *cmd)
{
	// log_info("%s", __func__);
	const char *device_str;
	const char *rev_str = NULL;

	device_str = "cw32";
	rev_str = "B";
	command_print_sameline(cmd, "%s - Rev: %s", device_str, rev_str);

	return ERROR_OK;
}

COMMAND_HANDLER(cw32_handle_user_command)
{
	struct target *target = NULL;
	struct cw32_flash_bank *cw32_info = NULL;
	struct flash_bank *bank;

	if (CMD_ARGC < 1)
		return ERROR_COMMAND_SYNTAX_ERROR;

	int retval = CALL_COMMAND_HANDLER(flash_command_get_bank, 0, &bank);
	if (retval != ERROR_OK)
		return retval;
	return retval;
}

static int cw32_load_fls_algo(struct flash_bank *bank)
{
	struct target *target = bank->target;

	int retval = 0;

	target_write_buffer(target, 0x20000, sizeof(fls_algo_buffer), fls_algo_buffer);

	// fls_algo_params.func_end = 0x20012;
	// struct armv7m_algorithm armv7m_info;	
	// armv7m_info.common_magic = ARMV7M_COMMON_MAGIC;
	// armv7m_info.core_mode = ARM_MODE_THREAD;	
	// struct armv7m_common *armv7m = target_to_armv7m(target);

	// retval = target_run_algorithm(target,
	// 							0, NULL,
	// 							0, NULL,
	// 							0x20001,
	// 							__BKPT,
	// 							10000, &armv7m_info);
	// log_info("cw32_load_fls_algo %d", retval);

	fls_algo_params.init = true;

	return retval;
}
    // cw32 load_fls_algo cw3065_flash_algo.elf
	// program cw3065_sdk_production.hex
static const struct command_registration cw32_exec_command_handlers[] = {
	{
		.name = "user",
		.handler = cw32_handle_user_command,
		.mode = COMMAND_EXEC,
		.usage = "bank_id",
		.help = "user",
	},
	COMMAND_REGISTRATION_DONE};

static const struct command_registration cw32_command_handlers[] = {
	{
		.name = "cw32",
		.mode = COMMAND_ANY,
		.help = "cw32 flash command group",
		.usage = "",
		.chain = cw32_exec_command_handlers,
	},
	COMMAND_REGISTRATION_DONE};

const struct flash_driver cw2213_flash = {
	.name = "cw2213",
	.commands = cw32_command_handlers,
	.flash_bank_command = cw32_flash_bank_command,
	.erase = cw32_erase,
	.protect = cw32_protect,
	.write = cw32_write,
	.read = default_flash_read,
	.probe = cw32_probe,
	.auto_probe = cw32_auto_probe,
	.erase_check = default_flash_blank_check,
	.protect_check = cw32_protect_check,
	.info = get_cw32_info,
	.free_driver_priv = default_flash_free_driver_priv,
};
